name: Test Coverage

on: [push, pull_request]

jobs:
  coverage:
    name: Go test coverage check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      
      - name: generate test generate coverage
        run: go test ./... -coverprofile=./cover.out

      - name: check test coverage
        id: coverage ## this step must have id
        uses: vladopajic/go-test-coverage@v2
        with:
          profile: cover.out
          local-prefix: github.com/org/project
          threshold-file: 80
          threshold-package: 80
          threshold-total: 90
      
      - name: make coverage badge
        uses: action-badges/core@0.2.2
        with:
          label: coverage
          message: ${{ steps.coverage.outputs.badge-text }}
          message-color: ${{ steps.coverage.outputs.badge-color }}
          file-name: coverage.svg
          badge-branch: badges
          github-token: "${{ secrets.GITHUB_TOKEN }}"